Personal Records/Models/DataContext.cs
using Personal_Records.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Personal_Records.Models
{
    public class DataContext : DbContext
    {
        public DbSet<PersonnelRecordsModel> PRModel { get; set; }
    }
}

Personal Records/Models/PersonnelRecordsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Personal_Records.Models
{
    [Table("personnel_records")]
    public class PersonnelRecordsModel
    {
        [Key]
        public int id { get; set; }     
        public string payroll_number { get; set; }
        public string forenames { get; set; }
        public string surname { get; set; }
        public string date_of_birth { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string address_2 { get; set; }
        public string post_code { get; set; }
        public string email_home { get; set; }
        public string start_date { get; set; }
    }
}

Personal Records/Controllers/PersonnelRecordsController.cs
using LumenWorks.Framework.IO.Csv;
using Personal_Records.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataTables;

namespace Personal_Records.Controllers
{
    public class PersonnelRecordsController : Controller
    {
        #region ConnectionVariables
        private static string constr = ConfigurationManager.ConnectionStrings["DataContext"].ToString();
        private SqlConnection con = new SqlConnection(constr);
        #endregion

        public ActionResult Index()
        {
            return View();
        }

        #region ParseCSVFile
        [HttpPost]
        public string ParseCSVFile(HttpPostedFileBase upload)
        {
            List<List<string>> allLineFields = new List<List<string>>();
            Stream stream = upload.InputStream;
            char delimiter = ',';
            using (CsvReader csvReader =
                new CsvReader(new StreamReader(stream), true, delimiter))
            {
                int fieldCount = csvReader.FieldCount;
                string[] headers = csvReader.GetFieldHeaders();

                while (csvReader.ReadNextRecord())
                {
                    List<string> fields = new List<string>(csvReader.FieldCount);
                    for (int i = 0; i < csvReader.FieldCount; i++)
                    {
                        try
                        {
                            string field = csvReader[i];
                            fields.Add(field.Trim('"'));
                        }
                        catch (MalformedCsvException ex)
                        {
                            throw;
                        }
                    }
                    allLineFields.Add(fields);
                }
            }
            return BulkInsert(allLineFields);
        }
        #endregion

        #region GetDataFromPersonnelRecords
        [HttpGet]
        public JsonResult GetAllPersonnelRecords()
        {
            using (DataContext db = new DataContext())
            {
                var cid = db.PRModel.SqlQuery("SELECT * FROM personnel_records order by surname asc").ToList();
                return Json(new { data = cid }, JsonRequestBehavior.AllowGet);
            }        
        }
        #endregion

        #region BulkInsertDataFromCSV
        public string BulkInsert(List<List<string>> lst)
        {
            int count = 0;
            var dt = new DataTable();
            dt.Columns.Add("id");
            dt.Columns.Add("payroll_number");
            dt.Columns.Add("forenames");
            dt.Columns.Add("surname");
            dt.Columns.Add("date_of_birth");
            dt.Columns.Add("telephone");
            dt.Columns.Add("mobile");
            dt.Columns.Add("address");
            dt.Columns.Add("address_2");
            dt.Columns.Add("post_code");
            dt.Columns.Add("email_home");
            dt.Columns.Add("start_date");
            try
            {
                for (int i = 0; i < lst.Count; i++)
                {
                    dt.Rows.Add("", lst[i][0], lst[i][1], lst[i][2], lst[i][3], lst[i][4], lst[i][5], lst[i][6], lst[i][7], lst[i][8], lst[i][9], lst[i][10]);
                    count++;
                }
                if (dt.Rows.Count > 0)
                {
                    using (var sqlBulk = new SqlBulkCopy(constr))
                    {
                        sqlBulk.BulkCopyTimeout = 5000;
                        sqlBulk.DestinationTableName = "dbo.personnel_records";
                        sqlBulk.WriteToServer(dt);
                        dt.Clear();
                    }
                }
                return count.ToString();
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        #endregion

        #region CRUDforDataTables
        [HttpPost]
        public ActionResult CRUD()
        {
            var request = System.Web.HttpContext.Current.Request;

            using (var db = new Database("sqlserver", constr))
            {
                var response = new Editor(db, "personnel_records", "id")
                    .Model<PersonnelRecordsModel>()
                    .Field(new Field("id")
                        .Set(false)
                        .Validator(Validation.Numeric())
                    )
                        .Process(request)
                    .Data();

                return Json(response);
            }
        }
        #endregion
    }
}

Personal Records/Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Personal_Records.Controllers
{
    public class UploadFileController : Controller
    {
        #region UploadCSVFile
        [HttpPost]
        public ActionResult UploadFiles()
        {
            string counter = "";
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {

                        HttpPostedFileBase file = files[i];
                        string fname;

                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        fname = Path.Combine(Server.MapPath("~/Uploads/"), fname);
                        file.SaveAs(fname);

                        using (PersonnelRecordsController pr = new PersonnelRecordsController())
                        {
                            counter = pr.ParseCSVFile(file);
                        }
                    }
                    return Json("File Uploaded Successfully! " + counter + " row(s) were successfully processed");
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("No files selected.");
            }
        }
        #endregion
    }
}

Personal Records/Views/PersonnelRecords/Index.cshtml
@{
    ViewBag.Title = "Personnel Records";
}
<div class="row">
    <div class="input-group">
        <div class="custom-file">
            <input type="file" accept=".csv" class="custom-file-input" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04">
            <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
        </div>
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="inputGroupFileAddon04">Button</button>
        </div>
    </div>
    <div style="margin:50px auto">
        <table id="personnelRecords" class="display" cellspacing="0" data-page-length='5'>
            <thead>
                <tr>
                    <th>Payroll number</th>
                    <th>Forenames</th>
                    <th>Surname</th>
                    <th>Date of Birth</th>
                    <th>Telephone</th>
                    <th>Mobile</th>
                    <th>Address</th>
                    <th>Address 2</th>
                    <th>Postcode</th>
                    <th>Email home</th>
                    <th>Start date</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

Personal Records/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Personnel Records</title>    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jqc-1.12.4/moment-2.18.1/dt-1.10.20/b-1.6.1/sl-1.3.1/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/datatables/css/generator-base.css">
    <link rel="stylesheet" type="text/css" href="~/Content/datatables/css/editor.dataTables.min.css">
    @Scripts.Render("~/bundles/modernizr")
    <!--<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css" />-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Personnel Records", "Index", "PersonnelRecords")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")                              g
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/v/dt/jqc-1.12.4/moment-2.18.1/dt-1.10.20/b-1.6.1/sl-1.3.1/datatables.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="~/Content/datatables/js/dataTables.editor.min.js"></script>
    <script type="text/javascript" src="~/Scripts/scripts.js"></script>
</body>
</html>